### ISSUE TITLE
Plugin doesn't start

### ISSUE THREAD

**Issue by Birowsky** [jlagerweij/elm-external-tools#2]
Hey there again, I finally got around to trying this. 
Here's what I'm seeing:
<img width="834" alt="screen shot 2018-02-17 at 18 01 13" src="https://user-images.githubusercontent.com/3199950/36343438-a4798372-140c-11e8-85aa-01e988c2d7dd.png">

<img width="422" alt="screen shot 2018-02-17 at 18 03 47" src="https://user-images.githubusercontent.com/3199950/36343465-f1841efc-140c-11e8-9233-8e190c5c736b.png">

> /usr/local/bin/elm-make:1 (function (exports, require, module, __filename, __dirname) { ���� ^ SyntaxError: Invalid or unexpected token at new Script (vm.js:51:7) at createScript (vm.js:138:10) at Object.runInThisContext (vm.js:199:10) at Module._compile (module.js:624:28) at Object.Module._extensions..js (module.js:671:10) at Module.load (module.js:573:32) at tryModuleLoad (module.js:513:12) at Function.Module._load (module.js:505:3) at Function.Module.runMain (module.js:701:10) at startup (bootstrap_node.js:193:16)

**Comment by jlagerweij** [comment]
Sorry to be this late to comment, but I suspect a mismatch in Node used to execute the elm-make and the Node version used to install elm-make. IntelliJ might use a different Node version, because of its difference in PATH with a normal terminal session. ElmExternalTools will try to use the node binary found right next to the elm-make by default, otherwise it uses the PATH to find the correct node binary. Make sure the correct node binary is in the same directory as elm-make (in your case /usr/local/bin). Please let me know if this fixes it, then I can add this info to the README.

**Comment by Birowsky** [comment]
No problem mate, thank you for you efforts!

So I just remembered that I was using a custom build of elm that fixes some performance bugs from the official 0.18 one. I'll give you a reference if you need it. 

Now I tried it with the official elm compiler and I get a different error:


<img width="388" alt="screen shot 2018-02-19 at 20 03 24" src="https://user-images.githubusercontent.com/3199950/36393460-f8fb9742-15af-11e8-996a-e3b1c8276f33.png">



> events.js:137 throw er; // Unhandled 'error' event ^ Error: spawn /myprojectpath/node_modules/elm/Elm-Platform/0.18.0/.cabal-sandbox/bin/elm-make ENOENT at _errnoException (util.js:1003:13) at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19) at onErrorNT (internal/child_process.js:389:16) at process._tickCallback (internal/process/next_tick.js:152:19) at Function.Module.runMain (module.js:703:11) at startup (bootstrap_node.js:193:16) at bootstrap_node.js:617:3


Let me know if I can give you any extra info. Or feel free to reach me on Slack!

**Comment by Birowsky** [comment]
Found the custom build: https://groups.google.com/forum/#!msg/elm-dev/c_BDwK5UXFs/NQcbzCN2EQAJ;context-place=forum/elm-dev

**Comment by jlagerweij** [comment]
I was able to reproduce your first error. I have installed `elm` using `brew install` and got the first error you reported when `node` was next to the `elm-make` binary. Elm-external-tools tries to use the node next to elm-make if it exists. Linux users reported errors otherwise. 

The second error I cannot reproduce, but might be because of the Node version being different on the normal terminal and within IntelliJ.

I plan to make a change in how the elm-make executable is called. If it is a script (so starts with a shebang) the elm-make is called with a configurable Node version. Otherwise it is an executable like your custom build of elm and can just be executed. 

Can you please check some things for me? Try to use the custom elm-dev build, but make sure there is no `node` executable in the same directory and let me know if this fixes the plugin?

**Comment by Birowsky** [comment]
Got some updates for you:

- Just reinstalled the plugin and it works! Looks Awesome! THanx.
- I'm even using it with a [different Elm plugin](https://github.com/durkiewicz/elm-plugin). The one you suggest freezes on me. Have no idea what the problem is.
- This one is strange: even tho you updated it, it doesn't seem to be reflected here:

<img width="910" alt="screen shot 2018-02-21 at 16 58 45" src="https://user-images.githubusercontent.com/3199950/36491144-61c37a9e-172a-11e8-9dd3-7f2e0e6299c9.png">

- I'm using now on a 30K lines codebase, so it sometimes takes 5-10 seconds to show the error messages. The problem is that if there are no errors, I don't know whether your plugin is done compiling, and so I just wait there :} Is there a possibility for you to add some kind of indicator that the plugin is doing some work?

**Comment by jlagerweij** [comment]
ElmExternalTools does require an Elm plugin to be installed, but it does not matter which one. 
Today the update was approved by Jetbrains and you should see the 1.1.0 update. It also reflects this in the Plugins of Intellij.
When you press the F2 button in Intellij it will tell you if there are no errors, or if error analysis is in progress. If you press F2, the green checkmark on the top-right will be updated too.

**Comment by Birowsky** [comment]
Oh dear. I just learned about a basic intellij feature. That indicator on the top-right is what i needed. Don't know why I chose to ignore it.

Again, great job and thank you!
